### ISSUE TITLE
java.io.FileNotFoundException: /nacos/v1/ns/operator/metrics

### ISSUE THREAD

**Issue by Naccl** [heqingpan/rnacos#21]
Nacos-Java-Client:v1.4.1

rnacos:v0.3.7  Release解压启动

启动服务时报错：

```
2023-09-29 17:25:56.832 ERROR  [on(8)-192.168.12.110] com.alibaba.nacos.client.naming          [ 617] : [NA] failed to request
java.io.FileNotFoundException: http://localhost:8848/nacos/v1/ns/operator/metrics?app=unknown&namespaceId=public
	at sun.reflect.GeneratedConstructorAccessor96.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1964)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1959)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1958)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1528)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1512)
	at com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse.getBody(JdkHttpClientResponse.java:60)
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handleError(AbstractResponseHandler.java:51)
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:44)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:483)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:427)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:603)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493)
	at com.alibaba.nacos.client.naming.net.NamingProxy.serverHealthy(NamingProxy.java:445)
	at com.alibaba.nacos.client.naming.NacosNamingService.getServerStatus(NacosNamingService.java:512)
	at com.alibaba.cloud.nacos.discovery.actuate.health.NacosDiscoveryHealthIndicator.doHealthCheck(NacosDiscoveryHealthIndicator.java:43)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37)
	at org.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoint.java:77)
	at org.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoint.java:40)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:130)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateContribution(HealthEndpointSupport.java:141)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:126)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:95)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:66)
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:71)
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:74)
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:121)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:96)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: http://localhost:8848/nacos/v1/ns/operator/metrics?app=unknown&namespaceId=public
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1910)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1512)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse.getStatusCode(JdkHttpClientResponse.java:75)
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:43)
	... 52 common frames omitted
2023-09-29 17:25:56.833 ERROR  [on(8)-192.168.12.110] com.alibaba.nacos.client.naming          [ 552] : request: /nacos/v1/ns/operator/metrics failed, servers: [localhost:8848], code: 500, msg: http://localhost:8848/nacos/v1/ns/operator/metrics?app=unknown&namespaceId=public
2023-09-29 17:25:57.215  INFO  [lient.naming.updater] com.alibaba.nacos.client.naming          [ 228] : new ips(1) service: DEFAULT_GROUP@@service@@DEFAULT -> [{"instanceId":"192.168.12.110#8010","ip":"192.168.12.110","port":8010,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@service","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2023-09-29 17:25:57.230  INFO  [lient.naming.updater] com.alibaba.nacos.client.naming          [ 267] : current ips:(1) service: DEFAULT_GROUP@@service@@DEFAULT -> [{"instanceId":"192.168.12.110#8010","ip":"192.168.12.110","port":8010,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@service","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2023-09-29 17:26:24.067  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 486] : [fixed-localhost_8848] [polling-resp] config changed. dataId=service, group=DEFAULT_GROUP
2023-09-29 17:26:24.075  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 486] : [fixed-localhost_8848] [polling-resp] config changed. dataId=service.yml, group=DEFAULT_GROUP
2023-09-29 17:26:24.076  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 598] : get changedGroupKeys:[service+DEFAULT_GROUP, service.yml+DEFAULT_GROUP]
2023-09-29 17:26:24.095  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 616] : [fixed-localhost_8848] [data-received] dataId=service, group=DEFAULT_GROUP, tenant=null, md5=, content=, type=null
2023-09-29 17:26:24.105  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 616] : [fixed-localhost_8848] [data-received] dataId=service.yml, group=DEFAULT_GROUP, tenant=null, md5=, content=, type=null
2023-09-29 17:26:24.263  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 486] : [fixed-localhost_8848] [polling-resp] config changed. dataId=service, group=DEFAULT_GROUP
2023-09-29 17:26:24.265  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 486] : [fixed-localhost_8848] [polling-resp] config changed. dataId=service.yml, group=DEFAULT_GROUP
2023-09-29 17:26:24.265  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 598] : get changedGroupKeys:[service+DEFAULT_GROUP, service.yml+DEFAULT_GROUP]
2023-09-29 17:26:24.270  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 616] : [fixed-localhost_8848] [data-received] dataId=service, group=DEFAULT_GROUP, tenant=null, md5=, content=, type=null
2023-09-29 17:26:24.273  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 616] : [fixed-localhost_8848] [data-received] dataId=service.yml, group=DEFAULT_GROUP, tenant=null, md5=, content=, type=null
2023-09-29 17:26:24.464  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 486] : [fixed-localhost_8848] [polling-resp] config changed. dataId=service, group=DEFAULT_GROUP
2023-09-29 17:26:24.466  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 486] : [fixed-localhost_8848] [polling-resp] config changed. dataId=service.yml, group=DEFAULT_GROUP
2023-09-29 17:26:24.466  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 598] : get changedGroupKeys:[service+DEFAULT_GROUP, service.yml+DEFAULT_GROUP]
2023-09-29 17:26:24.472  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 616] : [fixed-localhost_8848] [data-received] dataId=service, group=DEFAULT_GROUP, tenant=null, md5=, content=, type=null
2023-09-29 17:26:24.476  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 616] : [fixed-localhost_8848] [data-received] dataId=service.yml, group=DEFAULT_GROUP, tenant=null, md5=, content=, type=null
2023-09-29 17:26:24.660  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 486] : [fixed-localhost_8848] [polling-resp] config changed. dataId=service, group=DEFAULT_GROUP
2023-09-29 17:26:24.664  INFO  [fixed-localhost_8848] c.a.n.client.config.impl.ClientWorker    [ 486] : [fixed-localhost_8848] [polling-resp] config changed. dataId=service.yml, group=DEFAULT_GROUP
......
```

后面五行就一直重复

**Comment by heqingpan** [comment]
@Naccl 

`/nacos/v1/ns/operator/metrics` 这个不是面向client sdk的协议，目前没有实现。
后面会考虑先加个 mock这个接口避免报错。如果有强依赖就直接兼容。

从日志上看，`/nacos/v1/ns/operator/metrics` 这个只会请求一次，应该不影响主流程。

---

后面五行就一直重复这个现象应该是有点问题，我来看看这个点。

想确认下你在配置中心有配置dataId为`service ` ,`service.yml` 的配置信息吗？可能和没有配置有关。

**Comment by heqingpan** [comment]
我用Nacos-Java-Client:v1.4.1看看能不能在我这边复现这个问题。

**Comment by heqingpan** [comment]
已在本地复现这个问题：在1.4.1配置信息不存在的情况下会循环请求会触发这个问题。  (2.x client没有这个问题）

我会尽快修复，快的话今晚，慢的话明天应该能解决。

**Comment by heqingpan** [comment]
已在最新版本v0.3.8修复这个问题：

1. 修复1.x http协议对空配置监听时出现循环监听的问题。
2. mock `/nacos/v1/ns/operator/metrics`接口。
